"""add_student_id_to_schedule_assignments

Revision ID: 33f4cb2c44ba
Revises: 8512826fabd7
Create Date: 2025-10-08 12:04:28.188000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33f4cb2c44ba'
down_revision = '8512826fabd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_assignments', sa.Column('student_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_assignments', 'student_id')
    # ### end Alembic commands ###
