"""Add student scheduling tables

Revision ID: 7740fba22f9c
Revises: 
Create Date: 2025-10-02 16:47:18.332095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7740fba22f9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_app_settings_id'), 'app_settings', ['id'], unique=False)
    op.create_table('student_schedule_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_student_schedule_operations_id'), 'student_schedule_operations', ['id'], unique=False)
    op.create_table('student_schedule_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('externship', sa.Boolean(), nullable=True),
    sa.Column('pair_id', sa.String(length=20), nullable=True),
    sa.Column('group_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_schedule_students_id'), 'student_schedule_students', ['id'], unique=False)
    op.create_index(op.f('ix_student_schedule_students_student_id'), 'student_schedule_students', ['student_id'], unique=True)
    op.create_table('student_schedule_weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_label', sa.String(length=50), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_schedule_weeks_id'), 'student_schedule_weeks', ['id'], unique=False)
    op.create_table('student_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pair_id', sa.String(length=20), nullable=False),
    sa.Column('student1_id', sa.Integer(), nullable=False),
    sa.Column('student2_id', sa.Integer(), nullable=False),
    sa.Column('group_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['student1_id'], ['student_schedule_students.id'], ),
    sa.ForeignKeyConstraint(['student2_id'], ['student_schedule_students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pair_id')
    )
    op.create_index(op.f('ix_student_pairs_id'), 'student_pairs', ['id'], unique=False)
    op.create_table('operation_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['operation_id'], ['student_schedule_operations.id'], ),
    sa.ForeignKeyConstraint(['pair_id'], ['student_pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_tracking_id'), 'operation_tracking', ['id'], unique=False)
    op.create_table('schedule_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('time_slot', sa.String(length=20), nullable=False),
    sa.Column('chair', sa.String(length=20), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.String(length=50), nullable=True),
    sa.Column('patient_name', sa.String(length=100), nullable=True),
    sa.Column('pair_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['operation_id'], ['student_schedule_operations.id'], ),
    sa.ForeignKeyConstraint(['pair_id'], ['student_pairs.id'], ),
    sa.ForeignKeyConstraint(['week_id'], ['student_schedule_weeks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_assignments_id'), 'schedule_assignments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_assignments_id'), table_name='schedule_assignments')
    op.drop_table('schedule_assignments')
    op.drop_index(op.f('ix_operation_tracking_id'), table_name='operation_tracking')
    op.drop_table('operation_tracking')
    op.drop_index(op.f('ix_student_pairs_id'), table_name='student_pairs')
    op.drop_table('student_pairs')
    op.drop_index(op.f('ix_student_schedule_weeks_id'), table_name='student_schedule_weeks')
    op.drop_table('student_schedule_weeks')
    op.drop_index(op.f('ix_student_schedule_students_student_id'), table_name='student_schedule_students')
    op.drop_index(op.f('ix_student_schedule_students_id'), table_name='student_schedule_students')
    op.drop_table('student_schedule_students')
    op.drop_index(op.f('ix_student_schedule_operations_id'), table_name='student_schedule_operations')
    op.drop_table('student_schedule_operations')
    op.drop_index(op.f('ix_app_settings_id'), table_name='app_settings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
