"""add_cdt_code_to_operations

Revision ID: 7b1a135ca30c
Revises: 33f4cb2c44ba
Create Date: 2025-10-09 12:27:35.871252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1a135ca30c'
down_revision = '33f4cb2c44ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_assignments', 'student_id')
    op.add_column('student_schedule_operations', sa.Column('cdt_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_schedule_operations', 'cdt_code')
    op.add_column('schedule_assignments', sa.Column('student_id', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
