"""add_externship_date_fields

Revision ID: 8512826fabd7
Revises: 7740fba22f9c
Create Date: 2025-10-08 09:27:55.472915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8512826fabd7'
down_revision = '7740fba22f9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_schedule_students', sa.Column('externship_start_date', sa.Date(), nullable=True))
    op.add_column('student_schedule_students', sa.Column('externship_end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_schedule_students', 'externship_end_date')
    op.drop_column('student_schedule_students', 'externship_start_date')
    # ### end Alembic commands ###
